package Model;
// Generated 17/07/2019 12:24:18 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedNativeQueries;
import javax.persistence.NamedNativeQuery;
import javax.persistence.Table;

/**
 * CatMotivoTarjeta generated by hbm2java
 */

@NamedNativeQueries({
	@NamedNativeQuery(
	name = "sp_consulta_catmotivostarjeta_general",
	query = "SELECT sp_consulta_catmotivostarjeta_general()",
	resultClass = CatMotivoTarjeta.class
	)
})

@Entity
@Table(name = "cat_motivo_tarjeta")
public class CatMotivoTarjeta  implements java.io.Serializable {

    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "mt_id_motivo", updatable = false, nullable = false)
    private int mtIdMotivo;
    
    @Column(name = "mt_movimineto")
    private int mtMovimiento;
    
    @Column(name = "mt_motivo")
    private String mtMotivo;

    public CatMotivoTarjeta() {
    }

    public CatMotivoTarjeta(int mtIdMotivo, int mtMovimiento, String mtMotivo) {
       this.mtIdMotivo = mtIdMotivo;
       this.mtMovimiento = mtMovimiento;
       this.mtMotivo = mtMotivo;
    }
   
    public int getMtIdMotivo() {
        return this.mtIdMotivo;
    }
    
    public void setMtIdMotivo(int mtIdMotivo) {
        this.mtIdMotivo = mtIdMotivo;
    }
    public int getMtMovimiento() {
        return this.mtMovimiento;
    }
    
    public void setMtMovimiento(int mtMovimiento) {
        this.mtMovimiento = mtMovimiento;
    }
    public String getMtMotivo() {
        return this.mtMotivo;
    }
    
    public void setMtMotivo(String mtMotivo) {
        this.mtMotivo = mtMotivo;
    }

}


