package Model;
// Generated 17/07/2019 12:24:18 AM by Hibernate Tools 4.3.1



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private String cuentaNoCuenta;
     private int estadoCuenta;
     private Double saldoDisponible;

    public Cuenta() {
    }

	
    public Cuenta(String cuentaNoCuenta, int estadoCuenta) {
        this.cuentaNoCuenta = cuentaNoCuenta;
        this.estadoCuenta = estadoCuenta;
    }
    public Cuenta(String cuentaNoCuenta, int estadoCuenta, Double saldoDisponible) {
       this.cuentaNoCuenta = cuentaNoCuenta;
       this.estadoCuenta = estadoCuenta;
       this.saldoDisponible = saldoDisponible;
    }
   
    public String getCuentaNoCuenta() {
        return this.cuentaNoCuenta;
    }
    
    public void setCuentaNoCuenta(String cuentaNoCuenta) {
        this.cuentaNoCuenta = cuentaNoCuenta;
    }
    public int getEstadoCuenta() {
        return this.estadoCuenta;
    }
    
    public void setEstadoCuenta(int estadoCuenta) {
        this.estadoCuenta = estadoCuenta;
    }
    public Double getSaldoDisponible() {
        return this.saldoDisponible;
    }
    
    public void setSaldoDisponible(Double saldoDisponible) {
        this.saldoDisponible = saldoDisponible;
    }




}


