package Model;
// Generated 17/07/2019 12:24:18 AM by Hibernate Tools 4.3.1



/**
 * PuntoRecarga generated by hbm2java
 */
public class PuntoRecarga  implements java.io.Serializable {


     private String clave;
     private String organizacion;
     private String referencia;
     private Integer estado;

    public PuntoRecarga() {
    }

	
    public PuntoRecarga(String clave) {
        this.clave = clave;
    }
    public PuntoRecarga(String clave, String organizacion, String referencia, Integer estado) {
       this.clave = clave;
       this.organizacion = organizacion;
       this.referencia = referencia;
       this.estado = estado;
    }
   
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(String organizacion) {
        this.organizacion = organizacion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


