package Model;
// Generated 17/07/2019 12:24:18 AM by Hibernate Tools 4.3.1



/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private int tipoUsuario;
     private String nombreTipo;

    public TipoUsuario() {
    }

    public TipoUsuario(int tipoUsuario, String nombreTipo) {
       this.tipoUsuario = tipoUsuario;
       this.nombreTipo = nombreTipo;
    }
   
    public int getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(int tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }




}


