package Model;
// Generated 17/07/2019 12:24:18 AM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private int fkIdusuarioTipoUsuario;
     private String fkNoCuentaCuenta;
     private String usuarioTelefono;
     private String fotografia;
     private String email;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, String nombre, String primerApellido, String segundoApellido, int fkIdusuarioTipoUsuario, String fkNoCuentaCuenta) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.fkIdusuarioTipoUsuario = fkIdusuarioTipoUsuario;
        this.fkNoCuentaCuenta = fkNoCuentaCuenta;
    }
    public Usuario(int idUsuario, String nombre, String primerApellido, String segundoApellido, int fkIdusuarioTipoUsuario, String fkNoCuentaCuenta, String usuarioTelefono, String fotografia, String email) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.fkIdusuarioTipoUsuario = fkIdusuarioTipoUsuario;
       this.fkNoCuentaCuenta = fkNoCuentaCuenta;
       this.usuarioTelefono = usuarioTelefono;
       this.fotografia = fotografia;
       this.email = email;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public int getFkIdusuarioTipoUsuario() {
        return this.fkIdusuarioTipoUsuario;
    }
    
    public void setFkIdusuarioTipoUsuario(int fkIdusuarioTipoUsuario) {
        this.fkIdusuarioTipoUsuario = fkIdusuarioTipoUsuario;
    }
    public String getFkNoCuentaCuenta() {
        return this.fkNoCuentaCuenta;
    }
    
    public void setFkNoCuentaCuenta(String fkNoCuentaCuenta) {
        this.fkNoCuentaCuenta = fkNoCuentaCuenta;
    }
    public String getUsuarioTelefono() {
        return this.usuarioTelefono;
    }
    
    public void setUsuarioTelefono(String usuarioTelefono) {
        this.usuarioTelefono = usuarioTelefono;
    }
    public String getFotografia() {
        return this.fotografia;
    }
    
    public void setFotografia(String fotografia) {
        this.fotografia = fotografia;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


